-- 1. Create the daily_words table
CREATE TABLE IF NOT EXISTS public.daily_words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    level TEXT NOT NULL, -- 'A1', 'A2', 'B1', etc.
    word TEXT NOT NULL,
    definition_en TEXT,
    definition_tr TEXT,
    definition_es TEXT,
    definition_de TEXT,
    definition_fr TEXT,
    definition_it TEXT,
    definition_jp TEXT,
    definition_kr TEXT,
    definition_cn TEXT,
    definition_ru TEXT,
    definition_pt TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(date, level) -- Ensures we don't have duplicates for the same level on same day
);

-- 2. Add tracking column to profiles
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS last_wotd_date DATE;

-- 3. Enable RLS (Row Level Security)
ALTER TABLE public.daily_words ENABLE ROW LEVEL SECURITY;

-- 4. Create Policy: Everyone can read daily words
CREATE POLICY "Everyone can read daily words" 
ON public.daily_words FOR SELECT 
USING (true);

-- 5. Create Policy: Only admins can insert/update (Optional, usually handled by service role or dashboard)
-- For now, we allow authenticated users to read.
