-- Create saved_questions table
CREATE TABLE IF NOT EXISTS public.saved_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, question_id)
);

-- Enable RLS
ALTER TABLE public.saved_questions ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can manage their own saved questions"
ON public.saved_questions
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
